server:
  port: 8007

spring:
  application:
    name: spring-boot-eureka-server

eureka:
  instance:
    # Eureka服务注册中心实例的主机名
    hostname: localhost
    # Eureka服务注册中心实例的应用名
    appname: spring-boot-eureka-server
    # Eureka服务注册中心实例的唯一ID
    instance-id:
    # Eureka服务注册中心实例的IP地址
    ip-address: 127.0.0.1

  client:
    # 与Eureka注册服务中心的通信zone和url地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    register-with-eureka: false
    # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always