spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          # RSA公钥访问地址
          jwk-set-uri: 'http://localhost:8081/rsa/publicKey'
  redis:
    host: 172.16.125.2
    port: 6379
    database: 0