# docker镜像环境
nacos_ip_port: 172.17.0.1:8848

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_ip_port}
      config:
        server-addr: ${nacos_ip_port}
        file-extension: yaml
