nacos:
  # Ubuntu-Docker环境
  ip: nacos-server
  # nacos端口
  port: 8848

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.ip}:${nacos.port}
      config:
        server-addr: ${nacos.ip}:${nacos.port}
        file-extension: yaml
  # mysql数据源配置
  datasource:
    url: jdbc:mysql://172.16.125.129:3306/eshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: fhc0618
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: 172.16.125.129
    port: 6379
    database: 0
    # 连接超时时间
    timeout: 20000ms

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # 实体扫描
  type-aliases-package: com.fhc.authenticationserver.entity
  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 表名是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
      # 主键类型 1.auto:数据库id自增 2.id_worker_str:全局唯一id(字符串类型) 3.uuid:全局唯一id(字符串类型)
      id-type: id_worker_str
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mybatis一级缓存，默认为session，同一个session下相同查询语句不会再次查询数据库
    local-cache-scope: session
    # 开启Mybatis二级缓存，默认为true
    cache-enabled: true

logging:
  level:
    com.fhc.authenticationserver: info