# 开发环境的认证中心ip和端口
auth_ip: localhost
auth_port: 8081

security:
  oauth2:
    authorization:
      check-token-access: http://${auth_ip}:${auth_port}/oauth/check_token
    client:
      access-token-uri: http://${auth_ip}:${auth_port}/oauth/token
      client-id: client_fhc
      client-secret: TONY0618
      scope: select
    resource:
      token-info-uri: http://${auth_ip}:${auth_port}/oauth/check_token
      # user-info-uri: http://${auth_ip}:${auth_port}/user
      id: resource-fhc



